### PR TITLE
Added compatibility with python3

### PR DESCRIPTION
**Pull request by safanaj**
This is to address #11 , I never used kitchen so I am not sure if the used approach to check multiple python version makes really sense.

### CODE REVIEW

**Comment by amendlik** [comment]
@safanaj Thank you for the issue report and the PR. The code change looks good, but I don't think the change to the test suite will help. Your change will cause Python 3 to be installed in the test containers, but it will still run the Python 2 version of Salt.

Would you please rebase these changes to include only the code change? I will figure out some way to test Python 3 and add it to the PR. Let me know if you need any help.

**Comment by safanaj** [comment]
@amendlik done, I left the kitchen unchanged

**Comment by safanaj** [comment]
I was thinking that passing `-x python3` to the provisioner bootstrap it would do the expected thing

**Comment by amendlik** [comment]
@safanaj After doing some research on this, I now see that you had it right the first time. The `-x` flag does cause it to install/run the python3 version of Salt. Any chance you could recover the earlier commit with your changes to `.kitchen`?

**Comment by safanaj** [comment]
@amendlik done. I had it in my reflog, thanks git ;)

**Pull request merged**
